// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    VarMessage: typeof import('./src/components/VarMessage.vue')['default']
    VarButton: typeof import('@varlet/ui/es')['Button']
  }
}

export { }
