// generated by unplugin-vue-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    VarActionSheet: typeof import('@varlet/ui')['_ActionSheetComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarDialog: typeof import('@varlet/ui')['_DialogComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarMessage: typeof import('./Users/qihao/varlet-vite-app/src/components/VarMessage.vue')['default']
    VarSticky: typeof import('@varlet/ui')['_StickyComponent']
    VarStyleProvider: typeof import('@varlet/ui')['_StyleProviderComponent']
    VarSwipe: typeof import('@varlet/ui')['_SwipeComponent']
    VarSwipeItem: typeof import('@varlet/ui')['_SwipeItemComponent']
    VarTab: typeof import('@varlet/ui')['_TabComponent']
    VarTabs: typeof import('@varlet/ui')['_TabsComponent']
    VarTest: typeof import('@varlet/ui')['_TestComponent']
  }
}

export { }
